name: musicblocks-test

on:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  musicblocks-docker-image-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: treehouses musicblocks
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="jleekwong/musicblocks"
          source .github/workflows/utils.sh
          music_arm_sha=$(get_manifest_sha "$repo:latest" "arm")
          echo $music_arm_sha
          nginx_arm_sha=$(get_manifest_sha "treehouses/nginx:latest" "arm")
          echo $nginx_arm_sha
          flag_arm=$(is_base "treehouses/nginx@"$nginx_arm_sha "$repo@"$music_arm_sha)
          echo $flag_arm
          music_amd64_sha=$(get_manifest_sha "$repo:latest" "amd64")
          echo $music_amd64_sha
          nginx_amd64_sha=$(get_manifest_sha "treehouses/nginx:latest" "amd64")
          echo $nginx_amd64_sha
          flag_amd64=$(is_base "treehouses/nginx@"$nginx_amd64_sha "$repo@"$music_amd64_sha)
          echo $flag_amd64
          music_arm64_sha=$(get_manifest_sha "$repo:latest" "arm64")
          echo $music_arm64_sha
          nginx_arm64_sha=$(get_manifest_sha "treehouses/nginx:latest" "arm64")
          echo $nginx_arm64_sha
          flag_arm64=$(is_base "treehouses/nginx@"$nginx_arm64_sha "$repo@"$music_arm64_sha)
          echo $flag_arm64
          flag=$(compare "treehouses/nginx@"$nginx_arm_sha "$repo@"$music_arm_sha "treehouses/nginx@"$nginx_amd64_sha "$repo@"$music_amd64_sha "treehouses/nginx@"$nginx_arm64_sha "$repo@"$music_arm64_sha)
          #echo $flag
          if [[ $flag == true ]]; then
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          #  build_image "treehouses/nginx:latest" arm "$repo" #base image is arm arch
          #  build_image "treehouses/nginx:latest" amd64 "$repo" #base image is amd64 arch
          #  build_image "treehouses/nginx:latest" arm64 "$repo" #base image is arm64 arch
          #  deploy_image "$repo" arm
          #  deploy_image "$repo" amd64
          #  deploy_image "$repo" arm64
